services:
  - type: worker
    name: telegram-delivery-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python telegram_delivery_bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SHEET_ID
        sync: false
      - key: GOOGLE_CREDS_JSON
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.3
